version: '2.1'

services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    command: /bin/sh -c "go run main.go"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - 8080:4549
    depends_on:
      - "mysql"

  mysql:
    image: docker.io/bitnami/mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/bitnami/mysql/data'
    environment:
      - MYSQL_DATABASE=fun_friends
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_password
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    healthcheck:
      test: [ 'CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh' ]
      interval: 15s
      timeout: 5s
      retries: 6

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 3535:80
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=mysql
    depends_on:
      - "mysql"

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/
      - ./www-html:/var/www/html
    command: [ nginx-debug, '-g', 'daemon off;' ]
    ports:
      - 80:80
    depends_on:
      - "mysql"
      - "app"
  # certbot:
  #   container_name: certbot
  #   image: certbot/certbot
  #   volumes:
  #     - ./etc-letsencrypt:/etc/letsencrypt
  #     - ./www-html:/var/www/html
  #   command: certonly --webroot --webroot-path=/var/www/html --email cheprasov.dev@gmail.com --agree-tos --no-eff-email -d cheprasov-personal.site
  #   depends_on:
  #     - nginx

volumes:
  etc-letsencrypt:
  mysql_data:
    driver: local
