version: '2.1'

services:
  go:
    build:
      context: .
      dockerfile: DockerFile
    command: /bin/sh -c "go run main.go"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - 8080:4549
    depends_on:
      - "mysql"
      - "web"

  mysql:
    image: docker.io/bitnami/mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/bitnami/mysql/data'
    environment:
      - MYSQL_DATABASE=fun_friends
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_password
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    healthcheck:
      test: [ 'CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh' ]
      interval: 15s
      timeout: 5s
      retries: 6

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 3535:80
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=mysql
    depends_on:
      - "mysql"
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/fun_friends.conf
    command: [ nginx-debug, '-g', 'daemon off;' ]

volumes:
  mysql_data:
    driver: local
